<?php

$title = 'My policy';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('policy', ['action' => 'add']) ?>">Add Policy</a>
</p>

<table class="table">
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Policy Number</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Premium</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($policys as $policy) : ?>
    <tr>
        <td><?= $this->escapeHtml($policy->first_name) ?></td>
        <td><?= $this->escapeHtml($policy->last_name) ?></td>
        <td><?= $this->escapeHtml($policy->policy_number) ?></td>
        <td><?= $this->escapeHtml($policy->start_date) ?></td>
        <td><?= $this->escapeHtml($policy->end_date) ?></td>
        <td><?= $this->escapeHtml($policy->premium) ?></td>
        <td>
            <a href="<?= $this->url('policy', ['action' => 'edit', 'id' => $policy->id, 'class'=>'btn btn-primary']) ?>">Edit</a>
            <a href="<?= $this->url('policy', ['action' => 'delete', 'id' => $policy->id, 'class'=>'btn btn-primary']) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>